# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file is the device-specific product definition file for
# smdk4x12. It lists all the overlays, files, modules and properties
# that are specific to this hardware: i.e. those are device-specific
# drivers, configuration files, settings, etc...

# Note that smdk4x12 is not a fully open device. Some of the drivers
# aren't publicly available in all circumstances, which means that some
# of the hardware capabilities aren't present in builds where those
# drivers aren't available. Such cases are handled by having this file
# separated into two halves: this half here contains the parts that
# are available to everyone, while another half in the vendor/ hierarchy
# augments that set with the parts that are only relevant when all the
# associated drivers are available. Aspects that are irrelevant but
# harmless in no-driver builds should be kept here for simplicity and
# transparency. There are two variants of the half that deals with
# the unavailable drivers: one is directly checked into the unreleased
# vendor tree and is used by engineers who have access to it. The other
# is generated by setup-makefile.sh in the same directory as this files,
# and is used by people who have access to binary versions of the drivers
# but not to the original vendor tree. Be sure to update both.



# These is the hardware-specific overlay, which points to the location
# of hardware-specific resource overrides, typically the frameworks and
# application settings that are stored in resourced.

LOCAL_PATH := device/hardkernel/odroidx2

include $(LOCAL_PATH)/BoardConfig.mk

#Device Files
$(call inherit-product-if-exists, vendor/hardkernel/odroidx2/odroidx2-vendor.mk)

DEVICE_PACKAGE_OVERLAYS := $(LOCAL_PATH)/overlay

ifeq ($(BOARD_USES_HGL),true)
PRODUCT_COPY_FILES += \
	$(LOCAL_PATH)/conf/egl.cfg:system/lib/egl/egl.cfg
endif

#ifeq ($(BOARD_USES_EMMC),true)
#PRODUCT_COPY_FILES += \
#	device/hardkernel/odroidx2/vold_emmc.fstab:system/etc/vold.fstab
#else
#PRODUCT_COPY_FILES += \
#	device/hardkernel/odroidx2/vold_sd.fstab:system/etc/vold.fstab
#endif

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/conf/fstab.odroidx2:root/fstab.odroidx2 

# Init files
#PRODUCT_COPY_FILES += \
#  device/hardkernel/odroidx2/conf/init.odroidx2.rc:root/init.odroidx2.rc
ifeq ($(BOARD_WLAN_DEVICE), rt5370sta)

PRODUCT_COPY_FILES += \
	device/hardkernel/odroidx2/conf/init.odroidx2.rc:root/init.odroidx2.rc 

else

PRODUCT_COPY_FILES += \
	device/hardkernel/odroidx2/conf/init.odroidx2_realtek.rc:root/init.odroidx2.rc 

endif
	
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidx2/conf/init.odroidx2.usb.rc:root/init.odroidx2.usb.rc 


# Kernel
ifeq ($(TARGET_PREBUILT_KERNEL),)
LOCAL_KERNEL := $(LOCAL_PATH)/kernel
else
LOCAL_KERNEL := $(TARGET_PREBUILT_KERNEL)
endif
PRODUCT_COPY_FILES += \
    $(LOCAL_KERNEL):kernel

#Prebuilt modules
PRODUCT_COPY_FILES += \
    device/hardkernel/odroidx2/modules/gator.ko:system/lib/modules/gator.ko \
    device/hardkernel/odroidx2/modules/rtl8191su.ko:system/lib/modules/rtl8191su.ko \
    device/hardkernel/odroidx2/modules/smsc95xx.ko:system/lib/modules/smsc95xx.ko \
    device/hardkernel/odroidx2/modules/uvcvideo.ko:system/lib/modules/uvcvideo.ko

#PRODUCT_COPY_FILES += \
#    device/hardkernel/odroidx2/modules/ansi_cprng.ko:system/lib/modules/ansi_cprng.ko \
#    device/hardkernel/odroidx2/modules/gator.ko:system/lib/modules/gator.ko \
#    device/hardkernel/odroidx2/modules/gpio_keys_polled.ko:system/lib/modules/gpio_keys_polled.ko \
#    device/hardkernel/odroidx2/modules/gspca_main.ko:system/lib/modules/gspca_main.ko \
#    device/hardkernel/odroidx2/modules/input-polldev.ko:system/lib/modules/input-polldev.ko \
#    device/hardkernel/odroidx2/modules/ramoops.ko:system/lib/modules/ramoops.ko \
#    device/hardkernel/odroidx2/modules/rtl8191su.ko:system/lib/modules/rtl8191su.ko \
#    device/hardkernel/odroidx2/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
#    device/hardkernel/odroidx2/modules/smsc95xx.ko:system/lib/modules/smsc95xx.ko \
#    device/hardkernel/odroidx2/modules/tcp_bic.ko:system/lib/modules/tcp_bic.ko \
#    device/hardkernel/odroidx2/modules/tcp_htcp.ko:system/lib/modules/tcp_htcp.ko \
#    device/hardkernel/odroidx2/modules/tcp_westwood.ko:system/lib/modules/tcp_westwood.ko


#BOARD_SEPOLICY_DIRS += \
#        device/hardkernel/odroidx2/sepolicy

#BOARD_SEPOLICY_UNION += \
#        file_contexts \
#        device.te \
#        dhcp.te \
#        domain.te \
#        file.te \
#        init_shell.te \
#        mediaserver.te \
#        pvrsrvinit.te \
#        system.te \
#        tee.te \
#        vold.te

#-------------------------------------------------------------------------------------
#
# WIFI firmware
#
#-------------------------------------------------------------------------------------
ifeq ($(BOARD_WLAN_DEVICE),rt5370sta)

PRODUCT_PROPERTY_OVERRIDES += \
	wifi.interface=ra0 \
	wifi.supplicant_scan_interval=15

else ifeq ($(BOARD_WLAN_DEVICE), rtl8191su)

PRODUCT_PROPERTY_OVERRIDES += \
	wifi.interface=wlan0 \
	wifi.supplicant_scan_interval=15
endif

# For V4L2
ifeq ($(BOARD_USE_V4L2), true)
ifeq ($(BOARD_USE_V4L2_ION), true)
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidx2/conf/ueventd.odroidx2.v4l2ion.rc:root/ueventd.odroidx2.rc
else
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidx2/conf/ueventd.odroidx2.v4l2.rc:root/ueventd.odroidx2.rc
endif
else
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidx2/conf/ueventd.odroidx2.rc:root/ueventd.odroidx2.rc
endif

# Include Launcher2 in build
PRODUCT_PACKAGES := \
	Launcher2


# Filesystem management tools
PRODUCT_PACKAGES += \
	make_ext4fs \
	setup_fs

# audio
PRODUCT_PACKAGES += \
	audio_policy.odroidx2 \
	audio.primary.odroidx2 \
	audio.a2dp.default \
	libaudioutils

PRODUCT_COPY_FILES += \
	device/hardkernel/odroidx2/conf/audio_policy.conf:system/etc/audio_policy.conf

# ULP Audio
ifeq ($(USE_ULP_AUDIO),true)
PRODUCT_PACKAGES += \
	libaudiohw \
	MusicULP \
	libsa_jni
endif

# ALP Audio
ifeq ($(BOARD_USE_ALP_AUDIO),true)
PRODUCT_PACKAGES += \
	libOMX.SEC.MP3.Decoder
endif

# Camera
PRODUCT_PACKAGES += \
	camera.$(TARGET_BOOTLOADER_BOARD_NAME)

# SEC_Camera
ifeq ($(USE_SEC_CAMERA),true)
PRODUCT_PACKAGES += \
	SEC_Camera
endif

# Libs
PRODUCT_PACKAGES += \
	libcamera \
	libhwjpeg \
	libstagefrighthw \
	com.android.future.usb.accessory

# Video Editor
PRODUCT_PACKAGES += \
	VideoEditorGoogle

# Mali
PRODUCT_PACKAGES += \
        libEGL_mali \
        libGLESv1_CM_mali \
        libGLESv2_mali \
        libMali \
        libUMP \
        libion2

# Misc other modules
PRODUCT_PACKAGES += \
	lights.$(TARGET_BOOTLOADER_BOARD_NAME) \
	hwcomposer.$(TARGET_BOOTLOADER_BOARD_NAME) \
	gralloc.$(TARGET_BOOTLOADER_BOARD_NAME) \
        libswscaler


# Widevine DRM
PRODUCT_PACKAGES += com.google.widevine.software.drm.xml \
	com.google.widevine.software.drm \
	WidevineSamplePlayer \
	test-libwvm \
	test-wvdrmplugin \
	test-wvplayer_L1 \
	libdrmwvmplugin \
	libwvm \
	libWVStreamControlAPI_L1 \
	libwvdrm_L1

# OpenMAX IL configuration files
PRODUCT_COPY_FILES += \
	device/hardkernel/odroidx2/media_profiles.xml:system/etc/media_profiles.xml \
	device/hardkernel/odroidx2/media_codecs.xml:system/etc/media_codecs.xml

# OpenMAX IL modules
PRODUCT_PACKAGES += \
	libSEC_OMX_Core \
	libSEC_OMX_Resourcemanager \
	libOMX.SEC.AVC.Decoder \
	libOMX.SEC.M4V.Decoder \
	libOMX.SEC.M4V.Encoder \
	libOMX.SEC.AVC.Encoder

# hwconvertor modules
PRODUCT_PACKAGES += \
	libhwconverter

PRODUCT_PACKAGES += \
	gps.$(TARGET_BOOTLOADER_BOARD_NAME)


#-------------------------------------------------------------------------------------
#
# framework permission file
#
#-------------------------------------------------------------------------------------
PRODUCT_COPY_FILES += \
	frameworks/native/data/etc/android.hardware.location.gps.xml:system/etc/permissions/android.hardware.location.gps.xml \
	frameworks/native/data/etc/android.hardware.wifi.xml:system/etc/permissions/android.hardware.wifi.xml \
	frameworks/native/data/etc/android.hardware.sensor.gyroscope.xml:system/etc/permissions/android.hardware.sensor.gyroscope.xml \
	frameworks/native/data/etc/android.hardware.touchscreen.multitouch.jazzhand.xml:system/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
	frameworks/native/data/etc/android.software.sip.voip.xml:system/etc/permissions/android.software.sip.voip.xml \
	frameworks/native/data/etc/android.hardware.usb.host.xml:system/etc/permissions/android.hardware.usb.host.xml \
	frameworks/native/data/etc/android.hardware.usb.accessory.xml:system/etc/permissions/android.hardware.usb.accessory.xml \
	packages/wallpapers/LivePicker/android.software.live_wallpaper.xml:system/etc/permissions/android.software.live_wallpaper.xml

# The OpenGL ES API level that is natively supported by this device.
# This is a 16.16 fixed point number
PRODUCT_PROPERTY_OVERRIDES := \
	ro.opengles.version=131072

PRODUCT_PROPERTY_OVERRIDES += \
	hwui.render_dirty_regions=false

# Widevine DRM
PRODUCT_PROPERTY_OVERRIDES += \
	drm.service.enabled=true

# Set default USB interface
PRODUCT_DEFAULT_PROPERTY_OVERRIDES += \
	persist.sys.usb.config=mass_storage

#ifeq ($(BOARD_USES_HIGH_RESOLUTION_LCD),true)
PRODUCT_CHARACTERISTICS := tablet

PRODUCT_COPY_FILES += \
	frameworks/native/data/etc/tablet_core_hardware.xml:system/etc/permissions/tablet_core_hardware.xml

$(call inherit-product, frameworks/native/build/tablet-dalvik-heap.mk)

PRODUCT_PROPERTY_OVERRIDES += \
	ro.sf.lcd_density=160

PRODUCT_AAPT_CONFIG := normal large tvdpi hdpi xhdpi

PRODUCT_AAPT_PREF_CONFIG := tvdpi

USE_PIXTREE_STAGEFRIGHT := false

# we have enough storage space to hold precise GC data
PRODUCT_TAGS += dalvik.gc.type-precise

## Installation helpers for the "OTA" packages

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/releasetools/installboot.sh:installboot.sh \
    $(LOCAL_PATH)/releasetools/install-emmc.sh:install-emmc.sh \
    $(LOCAL_PATH)/releasetools/README.txt:README.txt

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/recovery/postrecoveryboot.sh:recovery/root/sbin/postrecoveryboot.sh \
    $(LOCAL_PATH)/recovery/setup-recovery:system/bin/setup-recovery \
    $(LOCAL_PATH)/recovery/pseudorec-to-sd:system/bin/pseudorec-to-sd \
    $(LOCAL_PATH)/recovery/kernel:system/pseudorec/recovery-kernel \
    $(LOCAL_PATH)/recovery/recoveryboot.scr:system/pseudorec/boot.scr

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/conf/98netflix:system/etc/init.d/98netflix
